=== Summary of Key Findings

This thesis presented the development and evaluation of an autonomous multi-sensor fire detection node, leveraging sensor fusion and TinyML to achieve robust and reliable fire detection with a significant reduction in false alarms. The research successfully demonstrated that an intelligent, edge-deployed sensing node can overcome the limitations of traditional single-parameter systems. The key findings are summarized below:

-   *High Discriminatory Power of Sensor Fusion*: The integration of five heterogeneous sensor modalities—smoke, VOC, CO, IR flame, and temperature/humidity—provides a comprehensive physical fingerprint of combustion. The research proved that while individual sensors are susceptible to nuisance triggers, their intelligent fusion allows for the robust rejection of common false alarms like cooking steam and aerosols.
-   *CO as a "Truth Sensor"*: A critical empirical finding was the role of Carbon Monoxide (CO) as a primary differentiator for active combustion. While other gas sensors (VOC, Smoke) exhibited high sensitivity to non-fire vapors, CO levels remained stable in all tested false alarm scenarios, making it an essential "truth sensor" within the fusion logic.
-   *Feasibility of TinyML at the Edge*: The project successfully deployed a quantized INT8 neural network on the Renesas RA4M1 microcontroller. The model achieved 100% classification accuracy on the validation dataset while maintaining an inference latency of less than 100 ms, proving that high-performance machine learning is feasible on low-power, resource-constrained hardware.
-   *Efficiency of Asymmetric Multi-Processing*: The use of an AMP firmware architecture on the Arduino UNO R4 WiFi ensured that time-critical sensing and inference tasks remained deterministic. By offloading MQTT telemetry to the ESP32-S3 co-processor, the system maintained operational integrity even during network activity.
-   *Superiority of Three-Class Classification*: The transition from a binary fire/no-fire model to a three-class schema (including an explicit false_alarm class) significantly improved the system's ability to handle ambiguous environmental states. Providing the model with labeled examples of nuisance events was key to achieving a near-zero false alarm rate.
-   *Effectiveness of Hybrid Hardware-AI Decision Fusion*: The research identified a critical "generalization gap" in pure TinyML models when encountering "Clean Fire" signatures (high IR, low smoke). The implementation of a hybrid logic layer, combining probabilistic AI with deterministic hardware overrides and heuristic suppression, proved essential for ensuring life-safety reliability across a broader spectrum of fire types and environmental noise.

In conclusion, this research confirms that an intelligent edge-deployed fire detection system using multi-sensor fusion and TinyML can effectively distinguish between real fires, ambient conditions, and false alarms, thereby significantly enhancing fire safety.
