=== Sensor Fusion and TinyML at the Edge

The challenge of reliable fire detection is increasingly being addressed through the convergence of sensor fusion and Tiny Machine Learning (TinyML). Sensor fusion refers to the integration of data from multiple heterogeneous sensors to improve classification accuracy and robustness beyond what is possible with single-modality systems. In the context of fire detection, this involves identifying the cross-correlations between gas concentrations, IR radiation, and environmental variables @pathan2024multisensory.

==== Fusion Architectures for Fire Detection

Traditional fusion techniques often relied on hand-crafted heuristic rules or centralized processing. Rule-based systems combine sensor readings using logical operators (AND, OR, weighted sums), where each sensor's contribution is predetermined by an expert. While computationally trivial, these systems require extensive domain knowledge to design and are brittle when confronted with environmental conditions not anticipated during rule development. @khan2022recent survey rule-based multi-sensor fire detection systems and conclude that they consistently underperform data-driven approaches in environments with high sensor noise or cross-sensitivity.

Data-driven fusion, by contrast, learns the optimal combination of sensor inputs directly from labeled training data. @xiao2023hybrid compare feature-level fusion—where raw or processed sensor data is concatenated into a single feature vector—against decision-level fusion, where each sensor independently classifies and the results are combined by voting or averaging. Their experiments demonstrate that feature-level fusion consistently achieves higher accuracy (3–7% improvement) because it preserves the correlation structure between sensors that is lost in decision-level fusion. This finding directly informs the architecture of the _Autonomous Sensing Node_, which employs feature-level fusion by concatenating statistical features from all five sensor channels into a unified input vector for the neural network.

==== TinyML: From Cloud to Microcontroller

However, the rise of TinyML allows for the deployment of complex neural networks directly on low-power microcontrollers, such as those based on the ARM Cortex-M architecture. This "Edge AI" approach eliminates the latency and privacy concerns associated with cloud-based processing, enabling autonomous nodes to make life-safety decisions locally and in real-time @sailesh2022novel.

Research has demonstrated that quantized neural networks can achieve detection accuracies exceeding 98% while operating within the severe memory and computational constraints of embedded hardware @alajlan2022tinyml. A critical aspect of this workflow is model optimization, where techniques such as Post-Training Quantization (PTQ) are used to convert 32-bit floating-point weights into 8-bit integers, significantly reducing the model's footprint with minimal impact on accuracy @novac2021quantization. @das2025tiny further demonstrate that the combination of quantization with neural architecture search (NAS)—automated design of network topologies optimized for a target hardware platform—can produce models that achieve competitive accuracy while consuming less than 100 KB of Flash and 50 KB of RAM, well within the capabilities of the Renesas RA4M1 processor used in this research.

The deployment pipeline typically involves training a model in a high-level framework (e.g., TensorFlow, PyTorch), applying quantization, and converting the result to a C++ library that is compiled directly into the firmware. Platforms such as Edge Impulse automate this pipeline, providing integrated tools for data management, feature extraction, model training, and embedded deployment @hymel2023edge. By processing multi-sensor data at the edge, these intelligent nodes can identify the unique "fingerprint" of fire and reject localized false alarm triggers with high fidelity @meleti2024obscured.

This convergence of sensor fusion and TinyML establishes the technological foundation for the three-class classification approach adopted in this research, where the system explicitly learns to distinguish fire, no-fire, and false-alarm signatures rather than relying on a binary fire/not-fire decision boundary.
