== Research Objectives and Contributions <sec:research_objectives>

=== Primary Research Objectives

The primary goal of this research is to develop and validate an autonomous sensing node capable of intelligent fire detection through multi-modal sensor fusion and edge-deployed machine learning. Traditional fire detection systems often suffer from high false alarm rates because they rely on single-modality thresholds, which fail to distinguish between combustion byproducts and common household aerosols @muller2024classification. To address these limitations, this study pursues three core objectives. First, the research aims to design a robust sensor fusion framework that integrates particulate smoke, volatile organic compounds (VOC), carbon monoxide (CO), and infrared flame signatures. By leveraging the mathematical correlations between these distinct environmental variables, the system seeks to improve the reliability of fire detection in complex indoor environments where "nuisance" triggers are prevalent @zheng2022research.

The second objective focuses on the technical feasibility of deploying sophisticated neural networks on resource-constrained hardware. Specifically, this study evaluates the implementation of TinyML models on a 48MHz Cortex-M4 microcontroller, such as the Renesas RA4M1 found in the Arduino UNO R4 WiFi. For an edge intelligence unit to be viable for life-safety applications, it must maintain an inference latency of less than 100ms to ensure a near-instantaneous response to evolving fire threats @das2025tiny. This objective involves investigating model optimization techniques, including quantization and pruning, to balance classification accuracy with the memory and processing limits of the embedded platform.

Third, the research investigates the efficacy of a three-class classification paradigm (fire, no-fire, and false alarm) compared to traditional binary models. While most existing literature categorizes events simply as fire or no-fire, this binary approach frequently results in high false-positive rates when the model encounters intense non-fire triggers like cooking fumes or cleaning sprays @muller2024classification. By explicitly training the model to recognize the statistical signatures of these "false alarm" scenarios, this study seeks to enhance the precision of the actual fire classification and provide more actionable intelligence for building automation systems.

=== Scientific and Technical Contributions

This thesis provides several contributions to the field of intelligent fire safety and edge computing. A significant technical contribution is the development of a validated edge intelligence unit architecture that utilizes asymmetric multi-processing. In this configuration, the primary microcontroller manages real-time sensor acquisition and ML inference, while a dedicated co-processor handles the connectivity backbone for MQTT-based telemetry @das2025tiny. This modular design mimics established robotic controller architectures, ensuring that the critical "reflex" of fire detection remains autonomous and unaffected by network latency or connectivity failures.

Furthermore, this research contributes a unique multi-modal dataset specifically designed for three-class fire detection. Unlike many publicly available datasets that focus on visual fire detection or limited sensor arrays, the data generated in this study includes high-frequency (10 Hz) time-series measurements from five distinct sensing modalities across a wide range of real-world fire and false alarm scenarios. This dataset facilitates the analysis of class separability and the identification of "truth sensors"—such as carbon monoxide for combustion verification—that are essential for reducing false alarms in stationary autonomous nodes @zheng2022research.

Finally, the study provides a comprehensive performance benchmark of TinyML models on low-power Cortex-M4 hardware. By documenting the trade-offs between model complexity, RAM usage, and inference latency, this work offers a roadmap for the deployment of intelligent safety systems in environments where cost and power consumption are critical constraints. The results demonstrate that through careful optimization, it is possible to achieve high-accuracy, multi-class fire detection on hardware that traditionally lacked the computational capacity for advanced machine learning @das2025tiny.