#let global_glossary_data = (
  ("ADC (Analog-to-Digital Converter)", "A system that converts an analog signal into a digital signal."),
  ("ACH (Air Changes per Hour)", "A measure of the air volume added to or removed from a space in one hour, divided by the volume of the space."),
  ("Adam (Adaptive Moment Estimation)", "An optimization algorithm that can be used instead of the classical stochastic gradient descent procedure to update network weights iteratively based on training data."),
  ("AMP (Asymmetric Multi-Processing)", "A system architecture where multiple processors or cores operate independently, often with different roles or architectures."),
  ("ANN (Artificial Neural Network)", "A computational model inspired by the structure and function of biological neural networks."),
  ("Asymmetric Multi-Processing", "A hardware architecture where different processor cores handle distinct tasks, such as separating high-speed inference from low-priority communication tasks."),
  ("Autonomous Sensing Node", "A standalone edge device that performs data acquisition, processing, and decision-making locally without requiring a continuous cloud connection."),
  ("Backpropagation", "An algorithm used to calculate the gradient of a loss function with respect to the weights in a neural network."),
  ("Baseline", "A standard or reference point used for comparison."),
  ("Baseline Resistance ($R_0$)", "The electrical resistance of a gas sensor in clean air or a stable ambient environment."),
  ("Binary Classification", "A type of classification task where there are only two possible classes or outcomes."),
  ("Blackbody Radiation", "The electromagnetic radiation emitted by an idealized physical body that absorbs all incident electromagnetic radiation."),
  ("BOM (Bill of Materials)", "An itemized list of all hardware components and their associated unit costs required to build one instance of the system."),
  ("Burn-in Period", "A period of time where a sensor is powered on and operated to stabilize its performance and remove initial contaminants."),
  ("Chemo-resistive Effect", "The phenomenon where the electrical resistance of a material changes in response to the chemical adsorption of gas molecules."),
  ("Chimney Effect", "The movement of air into and out of buildings, chimneys, or other containers, resulting from air buoyancy."),
  ("Complementary Fusion", "A fusion strategy where sensors provide independent information about different aspects of the environment."),
  ("Convection", "The transfer of heat through the movement of a fluid (such as air)."),
  ("Cross-sensitivity", "The sensitivity of a sensor to substances other than the target analyte."),
  ("Data Forwarder", "A tool that allows for real-time streaming of sensor data from a device to the Edge Impulse studio."),
  ("Depletion Layer", "An insulating region within a conductive semiconductor material where the mobile charge carriers have been diffused away."),
  ("Differential Sensing", "A method of measurement where the change in a value relative to a baseline is more important than the absolute value."),
  ("DSP (Digital Signal Processing)", "The use of digital processing, such as by computers or specialized digital signal processors, to perform a wide variety of signal processing operations."),
  ("Edge AI", "The practice of processing artificial intelligence algorithms locally on a hardware device, rather than on a remote cloud server."),
  ("Edge Deployment", "The strategy of placing sensors and processing power at the \"edge\" of a network, directly at the site of data generation."),
  ("Edge Node", "A computing element that performs data processing at the \"edge\" of the network, near the source of the data, to reduce latency and bandwidth use."),
  ("EEPROM (Electrically Erasable Programmable Read-Only Memory)", "A type of non-volatile memory used in computers and other electronic devices to store small amounts of data."),
  ("Environmental Compensation", "The process of adjusting sensor readings to account for the influence of environmental factors like temperature and humidity."),
  ("Environmental Variance", "The range of different environmental conditions (temperature, humidity, air quality) encountered by a system."),
  ("EON Compiler", "Edge Impulse's deep learning compiler that optimizes models for low-power microcontrollers."),
  ("ESP-NOW", "A connectionless, peer-to-peer WiFi communication protocol developed by Espressif for low-latency data transfer between ESP32 devices."),
  ("ESP32-S3", "The secondary microcontroller on the Arduino UNO R4 WiFi responsible for WiFi and Bluetooth connectivity."),
  ("F1 Score", "A measure of a model's accuracy on a dataset, calculated as the harmonic mean of precision and recall."),
  ("False Alarm Rate (FAR)", "The frequency at which a system incorrectly indicates the presence of a target condition."),
  ("FDAS (Fire Detection and Alarm System)", "A complete system comprising detectors, control panels, and notification appliances, assessed as a whole under safety standards."),
  ("FFT (Fast Fourier Transform)", "An efficient algorithm for computing the Discrete Fourier Transform of a finite-length signal, decomposing it into constituent frequency components."),
  ("Field of View (FoV)", "The extent of the observable world that is seen at any given moment by a sensor or camera."),
  ("Flame flicker frequency", "The characteristic oscillation frequency (approximately 1–15 Hz) of turbulent diffusion flames, caused by periodic vortex shedding at the flame base."),
  ("Generalizability", "The ability of a machine learning model to perform accurately on new, unseen data that was not part of its training set."),
  ("Ground Loop", "An unwanted current path in a circuit that can cause signal interference and noise."),
  ("Heterogeneous Sensors", "A collection of sensors that use different physical principles or target different phenomena."),
  ("I2C Bus", "A multi-master, multi-slave, packet switched, single-ended, serial communication bus."),
  ("Impulse", "The complete data processing and learning pipeline within the Edge Impulse platform."),
  ("Inference Latency", "The time required for a deployed machine learning model to process an input and generate a classification output on the edge device."),
  ("INT8", "An 8-bit signed integer format."),
  ("IR-Transparent", "A material that allows infrared radiation to pass through it with minimal absorption or reflection."),
  ("JSON (JavaScript Object Notation)", "A lightweight data-interchange format that is easy for humans to read and write and easy for machines to parse and generate."),
  ("Kurtosis", "A fourth-order statistical moment measuring the heaviness of a distribution's tails; high kurtosis indicates impulsive, spike-like signal behaviour."),
  ("LDA (Linear Discriminant Analysis)", "A supervised dimensionality reduction method that finds projections maximising the ratio of between-class to within-class variance."),
  ("Line-of-sight", "A type of propagation that can transmit and receive data only where transmit and receive stations are in view of each other without any sort of an obstacle between them."),
  ("MEMS (Micro-Electro-Mechanical Systems)", "Technology of very small devices, often used for high-sensitivity gas and pressure sensors on a single chip."),
  ("Micro-heater", "A miniaturized heating element used in MEMS sensors to maintain the sensing material at its required operating temperature."),
  ("MLOps (Machine Learning Operations)", "A set of practices that aims to deploy and maintain machine learning models in production reliably and efficiently."),
  ("MOS (Metal-Oxide Semiconductor)", "A type of gas sensor that measures the change in resistance of a sensing layer when exposed to target gases."),
  ("MQTT (Message Queuing Telemetry Transport)", "A lightweight, publish-subscribe network protocol that transports messages between devices."),
  ("Multi-class Classification", "A classification task with more than two classes."),
  ("Multi-Layer Perceptron (MLP)", "A class of feedforward artificial neural network consisting of at least three layers of nodes."),
  ("Multi-modal Sensing", "A sensing strategy that utilizes multiple different types of sensors to gather information about an environment."),
  ("Notified Body", "A conformity assessment organisation designated by an EU member state to evaluate products against harmonised European standards."),
  ("Nuisance Alarm", "A false alarm triggered by non-hazardous environmental factors (e.g., steam, dust, or cooking) that mimics fire signatures."),
  ("Nuisance Event", "An environmental event that may trigger a sensor but does not represent a genuine hazard, such as cooking steam or cigarette smoke."),
  ("Nuisance Source", "A non-hazardous environmental stimulus that can trigger a sensor, such as cooking steam or cigarette smoke."),
  ("Nyquist–Shannon Sampling Theorem", "A fundamental bridge between continuous-time signals and discrete-time signals, stating that a signal can be perfectly reconstructed if it is sampled at a rate greater than twice its highest frequency component."),
  ("Overlap", "The portion of a sampling window that is shared with the previous or subsequent window."),
  ("PCA (Principal Component Analysis)", "An unsupervised linear transformation that projects data onto orthogonal axes of maximum variance, reducing dimensionality while retaining most information."),
  ("PLS-DA (Partial Least Squares Discriminant Analysis)", "A statistical method used for find a linear regression model by projecting the predicted variables and the observable variables to a new space."),
  ("Post-Training Quantization (PTQ)", "A technique to convert a pre-trained floating-point model to a quantized model with minimal accuracy loss and without retraining."),
  ("PPE (Personal Protective Equipment)", "Specialized clothing or equipment worn by employees for protection against health and safety hazards."),
  ("PRISMA", "Preferred Reporting Items for Systematic Reviews and Meta-Analyses; a standardized evidence-based minimum set of items for reporting in reviews."),
  ("Publish-Subscribe", "A messaging pattern where senders (publishers) do not send messages directly to specific receivers (subscribers), but instead characterize published messages into classes without knowledge of which subscribers there may be."),
  ("Pull-up Resistor", "A resistor used to ensure a known state for a signal line."),
  ("Quantization", "A model optimization technique that converts high-precision weights (e.g., 32-bit float) to lower-precision formats (e.g., 8-bit integer) to reduce memory usage and increase inference speed."),
  ("Quantization-Aware Training (QAT)", "A method where the model is trained with quantization effects in the loop to improve accuracy in low-precision deployments."),
  ("RA4M1", "The primary 32-bit ARM Cortex-M4 microcontroller on the Arduino UNO R4 WiFi."),
  ("Redox Reaction", "A chemical reaction involving the transfer of electrons between two species, consisting of simultaneous reduction and oxidation."),
  ("Redundant Fusion", "A fusion strategy where multiple sensors provide independent measurements of the same physical property."),
  ("ReLU (Rectified Linear Unit)", "A linear function that will output the input directly if it is positive, otherwise, it will output zero."),
  ("RMS (Root Mean Square)", "The square root of the mean of squared sample values, providing a measure of signal energy or effective amplitude over a window."),
  ("Sampling Frequency", "The number of samples per unit time taken from a continuous signal to make a discrete signal."),
  ("Selectivity", "The ability of a sensor to respond specifically to a target analyte while rejecting interference from other substances."),
  ("Self-heating", "The phenomenon where an electronic device or sensor increases in temperature due to its own internal power dissipation."),
  ("Sensitivity", "The ability of a sensor to detect small changes in the target analyte or physical property."),
  ("Sensor Fusion", "The process of combining data from multiple sensors to achieve higher accuracy and more reliable information than possible with single sensors."),
  ("SIMD (Single Instruction, Multiple Data)", "A type of parallel processing that allows one instruction to be applied to multiple data points simultaneously."),
  ("Smoldering", "A slow, low-temperature, flameless form of combustion, sustained by the heat evolved when oxygen directly attacks the surface of a condensed-phase fuel."),
  ("Smoke Dilution", "The reduction in smoke concentration due to mixing with clean air, often caused by strong ventilation or wind."),
  ("Softmax", "An activation function that turns a vector of numbers into a vector of probabilities that sum to one."),
  ("Specificity", "The ability of a test to correctly identify those without the condition (true negative rate)."),
  ("Spectral Leakage", "The phenomenon where signal energy at one frequency \"leaks\" into adjacent frequency bins in the FFT spectrum."),
  ("Spectral power", "The squared magnitude of a signal's Fourier coefficients within a specified frequency band, representing energy concentration at those frequencies."),
  ("Static Location Tagging", "Assignment of a fixed Zone_ID string to each node's MQTT payload at firmware configuration time."),
  ("STEL (Short-Term Exposure Limit)", "The maximum concentration of a chemical to which workers may be exposed continuously for a short period of time without any danger to health."),
  ("Sub-ppm", "Concentrations less than one part per million."),
  ("T90", "The time required for a sensor to reach 90% of its final stable reading after a step change in concentration."),
  ("Telemetry", "The automatic measurement and wireless transmission of data from remote sources."),
  ("Three-Class Classification", "A supervised learning approach that categorizes data into three distinct labels—in this context, identifying fire, normal background, or non-fire nuisance events."),
  ("TinyML", "A field of machine learning focused on deploying optimized models on low-power, resource-constrained microcontrollers at the hardware edge."),
  ("TWA (Time-Weighted Average)", "The average exposure to a contaminant over a specified period, usually an 8-hour workday."),
  ("UL (Underwriters Laboratories)", "A US-based safety certification organisation."),
  ("Veto Logic", "A decision-making strategy where a negative signal from a highly reliable sensor (truth sensor) can override positive signals from other sensors to prevent a false alarm."),
  ("Voltage Rail", "A single voltage provided by a power supply unit, such as 3.3V or 5V."),
  ("Welch Window", "A windowing function used in spectral analysis to reduce the influence of signal discontinuities at the edges of a data segment."),
  ("Window Size", "The duration of a signal segment used for a single inference or analysis."),
  ("Zone_ID", "A unique identifier assigned to a sensing node that represents its physical location in a building."),
)
