=== Evolution of Fire Detection and MEMS Technology

The technological trajectory of fire detection has evolved from simple thermal triggers to sophisticated multi-modal sensing platforms. Early fire safety relied on ionization and photoelectric sensors, which, while effective at identifying smoke particles, lacked the intelligence to contextualize the environment. The primary limitation of these legacy systems is their reliance on static thresholding of a single physical parameter, making them highly susceptible to false alarms from non-fire aerosols, such as cooking steam or dust @fonollosa2018chemical.

==== From Single Sensors to Gas Arrays

The recognition that single-parameter detection was insufficient led researchers to explore multi-gas sensor arrays as early as the 1990s. Initial efforts focused on combining carbon monoxide (CO) sensors with traditional smoke detectors, leveraging the observation that CO is a reliable marker of incomplete combustion. @wang2025enhanced provide a comprehensive review of this transition, noting that the addition of even a single gas channel to a smoke detector reduced false alarm rates by 40–60% in residential settings. However, these early multi-sensor systems still relied on deterministic threshold logic (e.g., "alarm if smoke > X AND CO > Y"), which, while an improvement, could not capture the complex, non-linear correlations between multiple environmental variables.

The advent of Micro-Electro-Mechanical Systems (MEMS) has fundamentally changed this landscape. MEMS technology allows for the miniaturization of complex chemical and physical sensors, enabling the integration of multiple sensing modalities into a single, compact node. Modern metal-oxide (MOS) sensors for Smoke, Volatile Organic Compounds (VOCs), and Carbon Monoxide (CO) offer high sensitivity and rapid response times within a footprint of only a few millimeters @pathan2024multisensory. These sensors operate by measuring changes in electrical resistance as gas molecules are adsorbed onto a heated sensing layer, a process that can be precisely controlled and monitored by microcontrollers. The reduction in size and cost has made it economically feasible to deploy arrays of four or more gas sensors in a single detection node, a configuration that was previously limited to industrial or laboratory-grade instruments.

==== The Role of Infrared Flame Detection

Furthermore, the integration of Infrared (IR) flame detection adds an optical dimension to the sensing suite. Unlike gas sensors, which detect the chemical byproducts of combustion, IR sensors identify the radiant emission of an open flame, specifically the characteristic flicker in the 760 nm to 1100 nm band @toreyin2012wavelet. This optical channel provides orthogonal information to the gas sensors: a genuine fire produces both chemical byproducts (CO, VOC, smoke particulates) and electromagnetic radiation (IR flicker), while most nuisance sources produce only a subset of these signatures.

However, IR-only detection carries its own vulnerabilities. @salhi2024early document that sunlight, halogen lighting, and reflective surfaces can produce IR signatures that mimic flame emission, particularly in indoor environments with large windows or glass facades. This finding underscores the necessity of multi-modal fusion: IR detection is most valuable not as a standalone trigger, but as a corroborating channel that, when combined with gas and smoke data, significantly increases the confidence of a fire classification.

The evolution toward "Autonomous Sensing Nodes" leverages these MEMS and IR advancements to create distributed intelligence units that can capture a comprehensive "physical fingerprint" of a fire event, providing the multi-dimensional data necessary for robust discrimination between genuine fires and environmental noise @meleti2024obscured. This multi-dimensional data, however, requires intelligent processing to be useful—threshold-based logic is insufficient for capturing the correlations between sensors. The following subsection examines how sensor fusion and TinyML address this challenge.
