== Multi-Modal Sensing Principles <sec:multimodal_sensing>

The efficacy of the _Autonomous Sensing Node_ is predicated on its ability to monitor diverse physical and chemical phenomena associated with combustion. Unlike legacy systems that rely on a single modality, multi-modal sensing leverages the cross-correlation between different environmental markers to reduce ambiguity. This section examines the theoretical principles of MEMS-based gas sensing and infrared (IR) flame detection, provides the scientific rationale for the sensor fusion architecture employed in this research, and discusses the theoretical framework for combining these modalities into a unified detection system.

=== Principles of MEMS Gas Sensing

Modern gas sensing for fire detection utilizes Micro-Electro-Mechanical Systems (MEMS) technology, which allows for the integration of heating elements and sensing layers on a sub-millimeter scale. The sensors used in this project—specifically for Carbon Monoxide (CO) and Volatile Organic Compounds (VOC)—operate on the chemiresistive principle. These sensors typically employ a metal-oxide semiconductor (MOS) sensing layer (e.g., $S n O_2$) deposited on a heated substrate. When the layer is heated to its operating temperature ($200 deg C - 400 deg C$), oxygen molecules from the air are adsorbed onto the surface, forming an electron-depletion layer that increases the sensor's electrical resistance.

Upon exposure to reducing gases such as CO or VOCs, these molecules react with the adsorbed oxygen, releasing electrons back into the conduction band and causing a measurable decrease in resistance @fonollosa2018chemical. The selectivity of these sensors is enhanced through the use of specific catalysts and precise temperature control. Carbon Monoxide is a particularly critical "truth sensor" because it is a direct byproduct of incomplete combustion, whereas many household aerosols (like cooking steam) produce high smoke or VOC readings but negligible CO spikes @Milli2025Reducing.

However, MEMS gas sensors are not without their limitations, and understanding these constraints is essential for designing a robust fusion system. The primary challenge is _cross-sensitivity_: MOS-based sensors respond to a broad class of reducing gases rather than a single target analyte. A VOC sensor based on $S n O_2$ will exhibit some response to CO, ethanol, methane, and hydrogen, making it difficult to attribute a resistance change to a specific gas without additional context @li2022research. This cross-sensitivity is precisely why multi-modal fusion is necessary—a single gas sensor cannot reliably identify a fire, but a combination of gas sensors with different selectivity profiles, combined with smoke and flame channels, can disambiguate the source.

A second challenge is _environmental drift_: MOS sensors exhibit gradual changes in baseline resistance over time due to aging of the sensing layer, poisoning by silicones or sulfur compounds, and sintering of the catalyst at high operating temperatures. @arshad2022fault survey fault detection mechanisms for gas sensor arrays, noting that without periodic re-calibration or adaptive baseline algorithms, sensor drift can degrade classification accuracy by 10–20% over a six-month period. This limitation is acknowledged in the _Autonomous Sensing Node_ design and constitutes a key area for future improvement, as discussed in the Future Work section.

Despite these challenges, MEMS gas sensors remain the preferred choice for compact fire detection nodes due to their small form factor, low power consumption (typically 10–50 mW), rapid response time (under 5 seconds for significant gas concentrations), and low unit cost. These characteristics make them suitable for deployment in residential and commercial environments where traditional analytical instruments (such as non-dispersive infrared CO detectors) would be prohibitively expensive or physically impractical.

=== Infrared Flame Detection Mechanisms

Flame detection relies on the observation of the electromagnetic radiation emitted by the high-temperature chemical reactions within a fire. The primary marker for hydrocarbon-based fires is the emission spectrum of carbon dioxide ($C O_2$), which exhibits a characteristic peak in the mid-infrared range at approximately $4.3 \mu m$. However, for low-cost edge nodes, near-infrared (NIR) sensors—such as the one utilized in this project—monitor the $760 n m$ to $1100 n m$ range.

These sensors utilize the photoelectric effect, where incident IR photons generate a current in a semiconductor junction. The theoretical challenge in IR detection is the presence of environmental noise, such as solar radiation or incandescent lighting, which can mimic the steady-state IR signature of a flame. Advanced nodes mitigate this through temporal analysis of the signal's "flicker" frequency (typically $1 H z - 30 H z$), which is a characteristic physical property of uncontrolled diffusion flames @toreyin2012wavelet.

The flicker phenomenon arises from the turbulent mixing of fuel and oxidizer in a diffusion flame, which produces quasi-periodic oscillations in the flame's radiation output. @park2020early demonstrate that this temporal signature can be extracted using simple time-domain analysis—calculating the variance of the IR signal over a short sliding window—without requiring computationally expensive frequency-domain transforms such as the Fast Fourier Transform (FFT). This finding is significant for embedded deployment, as it implies that meaningful flame verification can be performed on a resource-constrained MCU without exceeding the available computational budget.

However, IR flame sensors are susceptible to a specific class of false positives: _steady-state IR emitters_ such as sunlight, halogen lamps, and heated surfaces. While flicker analysis can distinguish a flickering flame from a constant source, it cannot distinguish a flickering flame from other modulated IR sources, such as sunlight filtered through blinds or reflections off moving objects. @salhi2024early investigate multi-band IR approaches that compare the ratio of radiation at different wavelengths to distinguish flame emissions from background sources, but these techniques require more complex and expensive sensor hardware than the single-channel NIR approach used in the _Autonomous Sensing Node_.

This vulnerability is addressed in the _Autonomous Sensing Node_ through the hybrid decision logic described in the Implementation chapter: IR detection is not used as a standalone trigger but is instead correlated with gas and smoke readings to confirm the presence of a genuine combustion event.

=== Theoretical Framework for Sensor Fusion

The integration of these diverse modalities into a single decision-making framework is grounded in the theory of data fusion. The Joint Directors of Laboratories (JDL) data fusion model, widely cited in multi-sensor system design, defines several levels of fusion ranging from raw data combination to higher-level situational assessment. For the _Autonomous Sensing Node_, the relevant fusion level is _feature-level fusion_, where extracted features from each sensor channel are combined into a single representation that is then classified by a machine learning model.

By combining complementary data (e.g., gas concentrations) and redundant data (e.g., smoke and IR), the system can navigate the "Heat Paradox"—the observation that false alarm sources often exhibit higher thermal signatures than early-stage fires @solorzano2021early. In a multi-modal architecture, the presence of smoke without a corresponding spike in CO or a characteristic IR flicker can be statistically categorized as a _false_alarm_ with high confidence. This "Physical Fingerprinting" approach ensures that the _Autonomous Sensing Node_ remains resilient against environmental interference while maintaining high sensitivity to genuine combustion events @muller2024classification.

The theoretical justification for multi-modal fusion rests on the principle of _orthogonal information_: each sensing modality provides information about a different physical or chemical aspect of the combustion process. Smoke sensors detect particulate matter, CO sensors detect a specific gaseous combustion product, VOC sensors detect a broader class of organic gases, IR sensors detect electromagnetic radiation, and temperature sensors detect thermal energy. A genuine fire produces a _correlated_ signature across all these modalities—smoke increases alongside CO, while IR flicker accompanies rising temperature. Nuisance sources, in contrast, typically produce elevated readings in only a subset of channels: cooking produces smoke and VOC but minimal CO; steam produces humidity and some smoke response but no CO or IR; direct sunlight produces IR but no gas response. This correlation structure is precisely what a trained neural network learns to exploit.

@pathan2024multisensory provide experimental evidence for the superiority of feature-level fusion over decision-level fusion (where each sensor independently classifies and the results are combined by voting or weighted averaging) in multi-sensor fire detection. Their experiments show that feature-level fusion achieves 3–7% higher classification accuracy than decision-level fusion, with the gap increasing in the presence of sensor noise or missing channels. This finding supports the architectural decision in the _Autonomous Sensing Node_ to concatenate all sensor features into a single vector for neural network classification, rather than implementing per-sensor classifiers with a post-hoc combination rule.

=== Section Glossary

- *Chemiresistive Sensing*: A sensing mechanism where the electrical resistance of a material changes in response to the chemical adsorption of gas molecules.
- *Metal-Oxide Semiconductor (MOS)*: A class of materials commonly used in gas sensors due to their high sensitivity to redox reactions at their surface.
- *Incomplete Combustion*: A chemical reaction where a fuel is only partially oxidized, resulting in the production of Carbon Monoxide (CO) and soot rather than Carbon Dioxide ($C O_2$).
- *Photoelectric Effect*: The physical phenomenon where light (photons) incident on a material causes the emission of electrons or the generation of an electrical current.
- *Physical Fingerprinting*: The technique of identifying a specific phenomenon (like fire) by observing the unique combination of multiple physical and chemical markers.
- *Cross-Sensitivity*: The tendency of a gas sensor to respond to non-target gases, reducing its selectivity for a specific analyte.
- *Feature-Level Fusion*: A data fusion strategy where extracted features from multiple sensors are combined into a single representation before classification.
