== Background <sec:background>

This section establishes the context for the research by examining the global impact of fire incidents and the critical shortcomings of current fire safety infrastructure. It begins by discussing the high rates of false alarms that lead to occupant desensitization and significant economic losses. The discussion then contrasts legacy systems with the capabilities of intelligent edge nodes, highlighting how multi-sensor fusion and on-device machine learning can address the limitations of single-parameter sensors.


=== Significance of Fire Detection and False Alarm Issues

Fire-related incidents continue to pose a severe threat to global life safety, infrastructure, and ecological stability. In 2024, the United States reported approximately 1.39 million fires, which resulted in 3,920 civilian deaths and an estimated \$19.1 billion in direct property damage. Beyond the residential domain, wildland fires have intensified due to shifting climate patterns; the 2024–2025 fire season recorded carbon emissions of approximately 2.2 Pg C, which is 9% above the historical average. These extreme wildfire events, particularly in the North American boreal forests and South American wetlands, underscore the urgent need for autonomous, rapid-response detection systems capable of operating in diverse environmental conditions.

However, the efficacy of modern fire safety infrastructure is severely undermined by the prevalence of false alarms, often referred to as nuisance alarms. In the United Kingdom, Home Office data for the 2020/21 period revealed that 98% of all incidents triggered by legacy systems were false alarms, with only 2% resulting from actual fires. Approximately 90% of these false positives are attributed to faulty apparatus or environmental interference rather than malicious intent. This "cry wolf" effect leads to dangerous occupant desensitization, where individuals may ignore or disable life-saving equipment due to frequent erroneous triggers.

The economic ramifications of these inaccuracies are profound. In the UK, false fire alarms cause annual losses exceeding £1 billion due to lost productivity and business disruption, with the average cost per instance estimated at £2,900. Similarly, regional reports from New South Wales, Australia, indicate that false alarms account for nearly 37% of total fire department responses, straining public resources and delaying deployment to genuine emergencies. Consequently, reducing the false alarm rate is a critical requirement for maintaining the integrity of fire services and public trust in safety technology.

=== Limitations of Legacy Systems vs. Intelligent Edge Nodes

Legacy fire detection systems primarily rely on single-parameter sensing, such as ionization or photoelectric smoke detection. While effective in specific scenarios, these sensors lack the granularity to distinguish between genuine combustion and common household or industrial non-fire aerosols. Photoelectric sensors are notoriously prone to interference from water vapor (steam), dust, and cooking fumes, while ionization sensors frequently trigger in response to high humidity or minor culinary activities. These single-modality systems operate on static thresholding, which fails to account for the complex, time-varying signatures of early-stage fires or the cross-correlation between temperature, gas concentrations, and light radiation.

The transition toward intelligent edge nodes—also termed _Autonomous Sensing Nodes_—offers a paradigm shift in detection reliability. By integrating a multi-sensor suite—incorporating Volatile Organic Compounds (VOC), Carbon Monoxide (CO), Infrared (IR) flame detection, and environmental variables (temperature and humidity)—a node can capture the multi-dimensional fingerprint of a fire event. Modern microcontrollers, such as the Arduino UNO R4 WiFi, feature an _Asymmetric Multi-Processing_ architecture that combines a high-performance Renesas Cortex-M4 core with a dedicated ESP32-S3 co-processor for connectivity. This setup is ideal for deploying Tiny Machine Learning (TinyML) models directly at the sensing site. It allows for real-time sensor fusion where the system processes high-frequency data (e.g., 10 Hz) across temporal windows (typically 10 s) to identify patterns that static thresholds overlook @khan2025advancements.

Unlike traditional sensors, these intelligent nodes utilize local inference to classify environments into three distinct states: fire, no_fire, and false_alarm. This classification framing significantly reduces latency by eliminating the need for cloud-based processing while preserving battery life through efficient on-device computation @alajlan2022tinyml. Research indicates that TinyML-driven multi-sensor fusion can achieve detection accuracies exceeding 98% while concurrently reducing false alarm rates to below 1%, effectively overcoming the physical limitations of legacy hardware @park2020early.
