== Research Questions <sec:research_questions>

=== Sensor Fusion for False Alarm Discrimination

The primary challenge in modern fire safety is the prevalence of unwanted alarms triggered by non-combustion aerosols, such as steam, cooking fumes, or cleaning sprays, which frequently deactivate automated detection systems @muller2024classification. While traditional single-modality detectors struggle with these "nuisance" triggers, multi-sensor data fusion—integrating particulate smoke, Volatile Organic Compounds (VOC), Carbon Monoxide (CO), and infrared flame signatures—offers a mathematically robust framework for optimal sensor integration under uncertainty @zheng2022research. Empirical evidence suggests that multi-sensor frameworks can reduce false alarms by up to 73% compared to conventional single-sensor systems @zheng2022research. This study evaluates whether a specific array of MEMS-based gas sensors and infrared detectors can reliably distinguish between active combustion and ambient environmental variances. Consequently, the first research question asks: _Can a multi-sensor fusion approach effectively discriminate between real fire events, normal ambient conditions, and common indoor false alarm triggers?_ This inquiry specifically focuses on the separability of multi-modal data in a stationary node context, targeting the identification of unique combustion signatures that remain distinct from household aerosols.

=== Real-Time TinyML Constraints on Cortex-M4 Platforms

Deploying sophisticated machine learning models on resource-constrained microcontrollers necessitates a rigorous balance between classification accuracy and execution speed @das2025tiny. The Cortex-M4 architecture, while widely adopted for its Digital Signal Processing (DSP) support, operates at lower clock frequencies than standard edge processors, such as the 48MHz Renesas RA4M1 utilized in the Arduino UNO R4 @das2025tiny. For fire detection systems to be considered safe for real-world application, inference latency must typically remain below 100ms to ensure near-instantaneous response times @das2025tiny. Existing research indicates that achieving such low latency often requires intensive model optimization, including quantization and pruning, to fit within the limited RAM and Flash memory of embedded devices @muller2024classification. This study seeks to determine the technical feasibility of running a fully integrated neural network on this low-power hardware without exceeding critical processing thresholds. Therefore, the second research question is: _Is TinyML deployment on a 48MHz Cortex-M4 microcontroller feasible for real-time fire detection while maintaining an inference latency of less than 100ms?_

=== Evaluation of Three-Class versus Binary Classification

Current fire detection literature is largely dominated by binary classification models that categorize events simply as "fire" or "no-fire" @muller2024classification. Such binary frameworks often lack the granularity to handle complex non-fire scenarios, frequently grouping false alarm triggers with either the fire class (leading to false positives) or the no-fire class (leading to high variance in the "normal" baseline) @muller2024classification. Advanced TinyML strategies now advocate for multi-class paradigms, where explicit "false alarm" labels allow the model to learn the specific statistical patterns of culinary activities or chemical sprays @das2025tiny. By providing the model with a dedicated class for nuisance triggers, it is hypothesized that the precision of the actual "fire" classification will improve significantly. This comparison is vital for understanding whether the increased complexity of a three-class model translates into tangible reliability gains in domestic and industrial environments. Thus, the third research question investigates: _How does three-class classification (fire/no_fire/false_alarm) compare to traditional binary classification in reducing false positive rates for intelligent fire detection nodes?_