== Physical Design and Enclosure

The physical design and enclosure of the autonomous fire detection node are engineered to optimize sensor exposure while maintaining the structural and thermal integrity of the electronic components. Unlike general-purpose electronics enclosures, a multi-sensor fire detection unit requires a specialized design that facilitates continuous gas exchange and provides robust isolation between internal heat sources and sensitive environmental probes.

=== Airflow Considerations for Gas Sensing

The primary requirement for the enclosure is to ensure that ambient air can freely circulate over the metal-oxide (MOS) gas sensor array. Because the detection of smoke, VOCs, and CO relies on the physical adsorption of gas molecules onto the sensing layer, any restriction in airflow can lead to significant detection delays, potentially exceeding the critical response window for incipient fires @fonollosa2018chemical.

The enclosure design utilizes a "ventilated chamber" approach, featuring strategically placed intake and exhaust vents that leverage natural convection. The heat generated by the sensors' internal micro-heaters creates a localized "chimney effect," where rising warm air draws in fresh ambient air from the lower vents. This passive airflow strategy ensures that the sensors are continuously exposed to a representative sample of the room's atmosphere without the need for active fans, which would increase power consumption and complexity @rasim2024fire.

=== Thermal and Modal Isolation

A secondary but equally critical design objective is the physical and thermal isolation of the node's constituent components.

==== Isolation of Environmental Sensors

As detailed in previous sections, the MOS gas sensors operate at high internal temperatures, generating localized heat that can skew environmental readings. To mitigate this, the node's layout follows a "modal isolation" strategy. The digital temperature and humidity sensor is positioned in a thermally isolated compartment, separated from the gas sensor array by a physical barrier or a minimum clearance distance @meleti2024obscured. This ensures that the sensor captures the true ambient conditions of the room rather than the self-heating effects of the device, which is essential for accurate cross-sensitivity compensation and "heat paradox" detection.

==== Optical Alignment for Flame Detection

The physical design also accounts for the line-of-sight requirements of the infrared flame sensor. The enclosure features a dedicated optical aperture with a clear IR-transparent window or an unobstructed opening, aligned to provide a 60-degree field of view @wang2023fire. This positioning ensures that the IR sensor can capture radiant emissions from open flames while being protected from mechanical damage and dust accumulation.
