== Problem Statement <sec:problem_statement>

=== Background and Problem Statement

The prevalence of false alarms in traditional fire detection systems remains a critical challenge for emergency response efficiency and public safety. Statistics from the United Kingdom Home Office indicate that approximately 98% of automatic fire alarm (AFA) incidents confirmed between 2020 and 2021 were false alarms, with 90% of these attributed to faulty or improperly maintained apparatus @ifsj2022report. Similar trends are observed in high-density urban infrastructure; for instance, the Taipei Metro reported a 94% false alarm rate between 2019 and 2024, where only 28 of 484 activations involved actual fire events @firesaf2025false. These frequent unwanted alarms lead to significant economic losses due to interrupted operations, the exhaustion of fire service resources, and a phenomenon known as "alarm fatigue," where occupants begin to ignore signals, thereby increasing the risk of casualties during real fire events @wang2023fire.

The high susceptibility to false positives stems largely from the limitations of traditional single-sensor detectors, which typically rely on a single physical property such as ionization or light scattering. These devices struggle to differentiate between combustion-derived smoke and non-fire aerosols like steam, dust, or cooking fumes @hatip2024multisensory. Single-sensor architectures are fundamentally limited in their ability to classify complex environmental patterns, as smoke particles vary significantly in composition and density @hatip2024multisensory. Furthermore, traditional rule-based algorithms often lack the flexibility to adapt to varying ambient conditions, resulting in either high false alarm rates or delayed response times @edgeimpulse2026fire.

To address these vulnerabilities, there is a growing need for intelligent multi-sensor fusion systems deployed at the network edge. Recent advancements in Tiny Machine Learning (TinyML) enable the execution of complex neural networks on resource-constrained microcontrollers, such as the ARM Cortex-M4 @moosmann2024tinyissimoyolo. By integrating heterogeneous data from gas, thermal, and optical sensors, these systems can identify cross-sensor correlations that are characteristic of true fire signatures @wang2023fire. However, a significant gap remains in developing low-power, cost-effective nodes that can provide three-class classification—distinguishing between "Fire," "No Fire," and specific "False Alarm" triggers—to minimize unnecessary emergency dispatches @edgeimpulse2026fire.

=== Scope and Limitations

This research focuses on the development and validation of a stationary "Autonomous Node" for indoor fire detection, utilizing an Arduino-based hardware platform. The system is designed to provide continuous 24/7 monitoring of specific indoor zones by fusing data from a multi-modal sensor array, including Micro-Electro-Mechanical Systems (MEMS) smoke, volatile organic compound (VOC), and carbon monoxide (CO) sensors, alongside infrared (IR) flame detection and environmental temperature/humidity sensing @rasimmax2024fire. Unlike mobile robotic platforms or Unmanned Aerial Systems (UAS) used for forest fire patrol, the stationary node is optimized for fixed installation in residential or commercial environments where high-fidelity, localized monitoring is required @meleti2024obscured.

The scope of this project is strictly limited to indoor fire detection scenarios. The sensor suite is selected to detect common indoor fire signatures; however, the detection range is limited by the physical sensitivity of the MEMS gas sensors and the line-of-sight requirements of the IR flame sensor @edgeimpulse2026fire. While the system leverages an Arduino UNO R4 WiFi for processing and communication, the research emphasizes TinyML model efficiency, specifically targeting a 32-bit Cortex-M4 architecture with limited SRAM @moosmann2024tinyissimoyolo. The system does not address active fire suppression or complex multi-node mesh networking, focusing instead on the accuracy of the individual node's classification capabilities. Furthermore, while the node can operate on battery power, long-term deployment strategies for energy harvesting or extreme low-power sleep modes are considered secondary to the primary objective of false alarm reduction through sensor fusion.