== The Autonomous Edge-Node Architecture

The "Autonomous Sensing Node" architecture developed in this research represents a paradigm shift from traditional, centralized fire detection systems toward intelligent, edge-deployed units capable of local decision-making. This architecture is physically and computationally centered on the Arduino UNO R4 WiFi, a versatile platform that enables the fusion of multi-modal sensor data with real-time TinyML inference. This section justifies the selection of this hardware platform and details the Asymmetric Multi-Processing (AMP) strategy that defines its operation.

=== Justification for the Arduino UNO R4 WiFi Platform

The selection of the Arduino UNO R4 WiFi as the primary controller was guided by three critical requirements: computational overhead for TinyML, multi-protocol connectivity, and ecosystem compatibility. Unlike its 8-bit predecessor (the UNO R3), the R4 WiFi is powered by the Renesas RA4M1 microcontroller, featuring a 32-bit ARM Cortex-M4 core running at 48 MHz @arduino2024.

This hardware upgrade provides the necessary 256 KB of Flash and 32 KB of SRAM required to host complex neural network models generated by the Edge Impulse platform. Furthermore, the RA4M1 includes a built-in Floating Point Unit (FPU) and support for DSP instructions (CMSIS-DSP), which are essential for high-frequency feature extraction, such as the 128-point FFTs used for flame flicker analysis @perez2023tinyml. The integration of an ESP32-S3 module alongside the RA4M1 provides a seamless bridge to modern IoT protocols without burdening the primary inference core, satisfying the requirement for real-time MQTT telemetry in stationary nodes.

=== Asymmetric Multi-Processing (AMP) Strategy

The core innovation of the R4 WiFi architecture is its Asymmetric Multi-Processing (AMP) capability, which allows for the functional separation of sensing, inference, and communication tasks across two distinct processing units.

==== The RA4M1 as the "Inference Brain"

In this node architecture, the Renesas RA4M1 serves as the "Inference Brain." It is responsible for the deterministic, time-critical tasks of the fire detection pipeline:
+ *Sensor Data Acquisition*: High-frequency sampling (10 Hz) of the five heterogeneous sensor modalities via I2C and high-resolution (14-bit) analog inputs.
+ *Digital Signal Processing (DSP)*: Local computation of mean, RMS, and spectral power features within sliding windows.
+ *TinyML Inference*: Execution of the quantized INT8 neural network model to classify the environment into fire, no_fire, or false_alarm states.

By isolating these tasks on the RA4M1, the system ensures that the sensing and inference loop is never interrupted by network latency or connectivity overhead @meleti2024obscured.

==== The ESP32-S3 as the "Connectivity Backbone"

The ESP32-S3 serves as the "Connectivity Backbone," acting as a specialized co-processor for wireless communication. It handles the high-level networking stack, including WiFi association, security protocols, and MQTT message serialization. When the RA4M1 identifies a significant event or reaches a classification consensus, it communicates the metadata to the ESP32-S3 via a dedicated serial bridge (UART). This modular approach allows the ESP32-S3 to manage telemetry and remote logging in the background, ensuring that the autonomous node remains responsive even during periods of heavy network traffic @rasim2024fire. This functional split between the "brain" and the "backbone" is critical for the reliability of life-safety systems, as it prevents communication failures from compromising local detection capabilities.
