== Sampling Parameters

The selection of appropriate sampling parameters — encompassing both the data acquisition rate and the temporal window over which observations are aggregated — is a foundational decision in any embedded time-series classification system. In the context of multi-sensor fire detection, these parameters govern whether the node captures the transient chemical signatures of combustion, the characteristic flicker dynamics of an open flame, and the slower thermal and gas-concentration drifts that distinguish genuine fire from nuisance events. Critically, the chosen parameters must simultaneously satisfy the physical requirements of each sensing modality and remain within the computational budget of a Cortex-M4 microcontroller running a quantized neural network in real time.

=== Sampling Frequency

The Nyquist–Shannon sampling theorem states that a signal must be sampled at a rate strictly greater than twice the highest frequency component of interest in order to avoid aliasing artefacts during reconstruction and feature extraction @samanta2024optimizing. In the context of infrared flame sensing, this constraint has concrete physical significance: turbulent, uncontrolled flames exhibit a wide-band flicker spectrum spanning 1–13 Hz, with the characteristic central frequency of approximately 10 Hz reported consistently in the combustion literature @toreyin2012wavelet. To satisfy the Nyquist condition for content up to the 13 Hz upper bound, a minimum acquisition rate of 26 Hz would be theoretically required for the IR channel alone; however, the present system adopts a unified, cross-modal sampling rate of 10 Hz (i.e., one sample vector every 100 ms) as a deliberate engineering trade-off.

This decision is justified by the response characteristics of the chemical sensing modalities. MEMS-based smoke, VOC, and CO sensors operate via transduction mechanisms whose physical response times typically range from several seconds to tens of seconds @vorwerk2024classification. Sampling these channels at rates substantially exceeding 10 Hz yields no additional information content, as successive readings are highly auto-correlated and dominated by sensor time-constants rather than by underlying environmental dynamics. The 10 Hz rate thus represents the practical upper bound imposed by the chemical sensor ensemble, ensuring that all channels within the fused input vector are acquired at a consistent, coherent cadence.

From a system-resource perspective, a 10 Hz sampling rate also aligns with the computational throughput of the Renesas RA4M1 (Cortex-M4 at 48 MHz) running the Edge Impulse inference engine. Research has demonstrated that reducing data acquisition rates on TinyML platforms can decrease RAM usage and inference latency by approximately 60–74% with minimal classification accuracy loss @samanta2024optimizing. The 10 Hz rate provides a 100 ms inter-sample interval that is comfortably shorter than the sub-second transient signatures associated with flaming combustion onset, while remaining well within the real-time budget required for continuous, non-blocking inference on the target hardware.

=== Window Size and Overlap Strategy

Once the per-sample cadence is established, the second critical parameter is the temporal window: the contiguous block of consecutive samples that is assembled into a single labeled instance and presented to the digital signal processing (DSP) block and subsequent classifier.

A 2-second window (20 samples at 10 Hz) was selected as the primary inference window for this system. This duration was chosen to capture sufficient temporal context to extract both time-domain statistical features (e.g., mean, root mean square, kurtosis) and frequency-domain features (e.g., spectral power in the 1–10 Hz flame-flicker band) from the IR channel with adequate frequency resolution. Research employed a 10-second window at a 10 Hz rate for an embedded fire detection CNN, demonstrating that windows of this order yield stable classification @deng2023indoor. A shorter 2-second window reduces the time-to-first-detection latency — a critical factor in life-safety applications — while still encoding the dominant sub-second chemical transients and flame-flicker energy.

Second, the window length directly determines the RAM footprint of the inference buffer on the RA4M1. At 10 Hz, five sensor channels, and single-precision representation, a 2-second window occupies a negligible fraction of the 128 KB SRAM available on the microcontroller, leaving ample headroom for the model weights, activation buffers, and firmware stack.

A 50% overlap (i.e., a new inference is triggered every 1 second, with the preceding 1-second block retained) is employed to increase temporal coverage and reduce the expected worst-case detection latency. With 50% overlap, a fire event that begins mid-window will be fully enclosed within the subsequent overlapping window, capping the maximum detection latency at one window stride (1 second) rather than one full window length (2 seconds). This sliding-window approach is standard practice in embedded TinyML classification pipelines @samanta2024optimizing.

For data collection, a capture duration of 10 seconds was used to provide sufficient samples for off-line model training and validation, ensuring that the resulting labeled training instances carry rich gas-concentration trend information — particularly important for distinguishing the gradual CO rise of smoldering combustion from the abrupt VOC spike of a cooking false-alarm event @vorwerk2024classification.
