== Evolution of Multi-Sensor Fire Detection <sec:evolution_of_sensing>

The detection of fire has historically relied on the observation of isolated physical or chemical markers, such as smoke particulate density or discrete temperature thresholds. While these methods provided a foundational layer of safety for the built environment, the inherent lack of contextual awareness in single-parameter sensing has consistently led to high false alarm rates and delayed detection of non-traditional combustion events. This section traces the evolution from these legacy thresholding systems to the modern paradigm of intelligent multi-sensor fusion, which forms the theoretical basis for the _Autonomous Sensing Node_ developed in this research.

=== Historical Context of Single-Threshold Detection

Early fire detection infrastructure was characterized by a "binary threshold" philosophy. Detectors were designed to trigger an alarm state only when a specific environmental variable exceeded a pre-defined limit. Ionization smoke detectors, the most widely deployed technology since the 1970s, operate by monitoring the electrical current passing between two charged plates within a small ionization chamber. When smoke particles enter the chamber, they disrupt the ion flow, reducing the current and triggering the alarm. Photoelectric detectors, introduced as a complementary technology, rely on the scattering of a collimated light beam by particulate matter within a sensing chamber @fonollosa2018chemical.

While both technologies are robust in controlled environments and remain mandated by building codes worldwide, they share a fundamental limitation: they are incapable of distinguishing between the carbonaceous soot of an active fire and the non-combustion aerosols produced by cooking fumes, steam from bathrooms, dust from construction, or aerosolized cleaning products. The NFPA reports that nuisance alarms—those triggered by non-fire sources—account for the vast majority of all fire alarm activations, with cooking being the leading cause in residential settings @nfpa2021code. This technological limitation has historically necessitated a trade-off between sensitivity and reliability, often resulting in systems that are either overly prone to nuisance alarms or dangerously unresponsive to "clean-burning" fires that produce minimal smoke.

The economic and behavioral consequences of this limitation are significant. Research by @FESTAG2016119 estimates that false fire alarms cost the United Kingdom approximately £1 billion annually when accounting for emergency service mobilization, business interruption, and occupant complacency. @RIGOS2019120890 further documents the "Cry Wolf" behavioral effect, whereby repeated exposure to false alarms leads occupants to ignore or actively disable fire detection systems, dramatically increasing the risk of casualty during genuine events. These findings underscore the urgent need for detection systems that can discriminate between genuine combustion and nuisance triggers at the sensor level.

=== The Shift Toward Multi-Modal Sensor Fusion

The limitations of single-modality systems led to the development of sensor fusion architectures, where multiple independent sensing channels are integrated into a single decision-making framework. The integration of chemical gas sensors—specifically targeting Carbon Monoxide (CO) and Volatile Organic Compounds (VOC)—alongside traditional smoke and thermal sensors has significantly enhanced the ability of systems to identify the chemical signature of combustion @wang2025enhanced. Unlike smoke particles, which can be mechanically filtered or obstructed, gas phase markers diffuse rapidly and provide an earlier indication of smoldering or incomplete combustion.

Research by @fonollosa2018chemical emphasizes that MEMS-based gas sensors allow for the creation of compact sensor arrays that can monitor multiple combustion byproducts simultaneously, providing a "physical fingerprint" that is far more resistant to environmental noise than any single-sensor approach. This concept of physical fingerprinting is central to the design philosophy of the _Autonomous Sensing Node_. Rather than relying on any single environmental marker, the system observes the _correlation_ between multiple markers—smoke density, CO concentration, VOC levels, IR flame signature, and temperature—to construct a multi-dimensional profile of the local environment.

Several fusion architectures have been proposed in the literature. The simplest approach is _voting-based fusion_, where each sensor independently produces a binary alarm decision and the system triggers only when a majority of sensors agree. While straightforward to implement, this method fails to capture the nuanced correlations between sensors. More sophisticated approaches include _Bayesian fusion_, where prior probabilities of fire are updated in real-time using sensor likelihoods, and _feature-level fusion_, where raw sensor data is concatenated into a single feature vector that is processed by a machine learning classifier @pathan2024multisensory. The latter approach has gained prominence with the rise of TinyML, as it allows the system to learn non-linear decision boundaries that would be impossible to specify manually.

The importance of CO as a "truth sensor" in multi-modal architectures deserves specific attention. @Milli2025Reducing demonstrate that CO is a near-universal byproduct of incomplete combustion, yet it is rarely produced at significant levels by common nuisance sources such as cooking steam, aerosol sprays, or water vapor. This selectivity makes CO an exceptionally reliable discriminator in a multi-sensor array. In contrast, VOC sensors, while highly sensitive to a broad range of organic compounds, exhibit significant cross-sensitivity to household products such as cleaning sprays and perfumes. The combination of CO with VOC monitoring therefore provides a complementary pair: high VOC with low CO suggests a nuisance source, while elevated levels of both indicate active combustion.

=== Modern Intelligent Fire Sensing Paradigms

Recent advancements in Edge Intelligence and Tiny Machine Learning (TinyML) have further transformed the fire detection landscape. Rather than relying on simple deterministic logic (e.g., IF Smoke > X AND Heat > Y), modern _Autonomous Sensing Nodes_ employ probabilistic models that learn the complex, non-linear correlations between different sensor inputs.

@su2022research present a comprehensive survey of machine learning approaches for fire detection, categorizing them into classical methods (Support Vector Machines, Random Forests, k-Nearest Neighbors) and deep learning methods (Convolutional Neural Networks, Recurrent Neural Networks, Long Short-Term Memory networks). Their analysis indicates that while classical methods achieve competitive accuracy on small, well-curated datasets, deep learning approaches consistently outperform them when the feature space is complex or the training data includes significant environmental variance. For gas-sensor array data specifically, @li2022research demonstrate that shallow neural networks with as few as two hidden layers can achieve classification accuracies exceeding 95% when trained on appropriately engineered features.

Systems utilizing temporal deep learning architectures—such as LSTM networks—can identify the temporal patterns associated with fire growth, distinguishing them from the transient spikes typical of false alarms @zhang2024multi. Furthermore, the use of hybrid feature fusion—combining raw sensor data with spectral analysis or temporal derivatives—allows for high-sensitivity detection even in the presence of intense background noise @wang2023hybrid.

However, the deployment of deep learning models on resource-constrained microcontrollers presents unique challenges that are not encountered in cloud-based or GPU-accelerated environments. @das2025tiny provide a systematic review of optimization techniques specifically targeting microcontroller deployment, including quantization-aware training, knowledge distillation, and neural architecture search. Their findings indicate that quantized shallow networks—architectures with 2–4 hidden layers and INT8 precision—represent the optimal trade-off between accuracy and resource utilization for Cortex-M class processors. This insight directly informs the model architecture selected for the _Autonomous Sensing Node_, as detailed in the Implementation chapter.

This transition from static hardware to software-defined sensing units enables a more resilient and adaptive fire safety infrastructure, capable of operating with minimal human intervention. The key enabling technology for this transition is TinyML, which is explored in detail in the following section.

=== Section Glossary

- *Autonomous Sensing Node*: A decentralized sensing unit capable of performing local data processing, pattern recognition, and decision-making without external supervision.
- *Sensor Fusion*: The process of combining data from multiple sensors to achieve more accurate and reliable information than could be obtained from any individual sensor.
- *Nuisance Alarm*: A false alarm triggered by a non-fire event that mimics one or more fire signatures, such as cooking steam or cigarette smoke.
- *Multi-Modal Sensing*: An approach that utilizes diverse sensing technologies (e.g., gas, optical, thermal) to monitor different physical or chemical aspects of a single phenomenon.
- *Physical Fingerprinting*: The technique of identifying a specific phenomenon by observing the unique combination of multiple physical and chemical markers.
