=== Literature Selection Strategy

The comprehensive literature review undertaken for this thesis systematically examined scholarly works published between 2015 and the present, ensuring an up-to-date understanding of advancements in intelligent fire detection systems. The primary focus of this selection strategy was threefold: multi-modal sensing, the application of TinyML for edge deployment, and innovative approaches to false alarm reduction. This targeted approach aimed to identify research that addresses the limitations of conventional fire detection systems, particularly their susceptibility to false positives.

The evolution of fire detection research has seen a significant shift from traditional threshold-based systems to more sophisticated, data-driven methodologies @alajlan2022tinyml. Early systems often relied on single-sensor thresholds, leading to high rates of false alarms caused by environmental interferents such as cooking fumes or steam @fonollosa2018chemical. To mitigate these issues, the current literature emphasizes the integration of multiple sensor modalities. Studies have explored combining temperature, smoke, flame, and carbon monoxide @solorzano2021early. The consistent identification of CO as a crucial differentiator between actual combustion events and false alarms in multi-sensor setups underlines the importance of multi-modal sensing strategies.

A critical aspect of the literature search involved identifying research pertaining to TinyML, particularly its application in resource-constrained edge devices like Arduino platforms. This area of study is vital for developing autonomous sensing nodes capable of real-time inference with minimal latency @sailesh2022novel. The integration of TinyML enables complex machine learning models to run directly on microcontrollers.

Furthermore, the literature selection prioritized studies focused on reducing false alarms, a pervasive challenge in fire detection. Research has moved beyond merely differentiating fire from non-fire conditions to more nuanced classification, including the explicit recognition of false alarm scenarios. This reflects a growing understanding that effective fire detection systems must not only reliably identify true fires but also robustly distinguish them from common nuisance sources like burnt toast, steam, and aerosols, which often present with similar sensor signatures @vorwerk2024classification.
