=== Contributions to the Field

The research presented in this thesis makes several significant contributions to the field of intelligent fire detection and edge computing. By shifting the focus from centralized, single-modality detection to autonomous, multi-sensor nodes, this work addresses the long-standing challenge of false alarm mitigation in residential and industrial environments.

==== Multi-Modal Sensor Fusion for High-Fidelity Discrimination

The primary contribution of this work is the empirical demonstration of 100% class separability between genuine fire events, ambient conditions, and common false alarm triggers using a heterogeneous five-sensor array. While traditional systems often struggle with the "heat paradox" or chemical overlap between smoke and steam, this research shows that the intelligent fusion of MOS gas sensors, IR flame detection, and environmental context provides a robust physical "fingerprint" of combustion @fonollosa2018chemical. The identification of the Carbon Monoxide (CO) sensor as a "truth sensor" within the fusion model provides a validated strategy for vetoing spurious alarms, a significant advancement over binary detection logic @LIU2023103733. This finding is particularly relevant for the fire safety industry, where CO monitoring has traditionally been treated as a separate concern from smoke detection rather than as an integral component of a unified classification system.

==== Optimized TinyML Deployment on Resource-Constrained Hardware

Secondly, this research contributes a validated framework for deploying quantized neural networks on commodity microcontrollers. By utilizing Post-Training Quantization (PTQ) to convert Multi-Layer Perceptrons to an 8-bit integer (INT8) representation, the system achieves a 4x reduction in memory footprint with minimal accuracy loss. The successful implementation on the Renesas RA4M1 demonstrates that real-time, high-frequency inference is achievable at the edge, even with high-dimensional feature vectors involving spectral analysis @sailesh2022novel. This provides a scalable blueprint for the next generation of autonomous sensing nodes that do not rely on persistent cloud connectivity for life-safety decisions @meleti2024obscured.

==== Three-Class Classification as an Architectural Pattern

A further contribution is the empirical validation of the three-class classification paradigm (fire / no_fire / false_alarm) as superior to traditional binary classification for false alarm reduction. By explicitly training the model on labeled examples of common nuisance triggers—cooking fumes, aerosol sprays, steam, and cleaning products—the system develops a more nuanced decision boundary that explicitly accounts for the data distributions most likely to cause false positives. The ablation study presented in the Results chapter demonstrates that the three-class model reduces false positive rates by an order of magnitude compared to an equivalent binary model trained on the same sensor data. This architectural pattern has implications beyond fire detection: any safety-critical classification system that faces known nuisance classes could benefit from explicit negative training rather than relying on the model to implicitly learn the boundary between "fire" and "everything else."

==== Hybrid Decision Architecture for Safety-Critical Edge Deployment

Finally, this work contributes the design and evaluation of a hybrid decision architecture that combines probabilistic AI inference with deterministic hardware safety overrides. The hybrid model addresses a fundamental challenge in deploying machine learning for safety-critical applications: the gap between laboratory accuracy and real-world reliability. By implementing a three-stage decision pipeline—AI probe, hardware verification, and critical override—the system achieves both high sensitivity (the AI model detects subtle multi-sensor patterns) and high reliability (hardware overrides ensure that obvious fire signatures are never missed, regardless of AI state). This layered approach provides a pragmatic template for other edge AI applications where a missed detection carries serious consequences, such as gas leak detection, structural health monitoring, or medical alert systems @muller2024classification.
