== Edge Impulse Project Setup

The implementation of a TinyML-based multi-sensor fire detection system requires a structured development environment capable of managing the full machine learning lifecycle — from raw sensor data ingestion to on-device inference deployment. This section describes the configuration of the Edge Impulse project environment as the foundational step in the implementation pipeline, covering platform rationale, project initialization, data ingestion strategy, and target hardware configuration.

=== Platform Rationale and Project Initialization

Embedded machine learning development presents a distinctive set of challenges that distinguish it from conventional cloud-based workflows. Research identifies several systemic obstacles in the TinyML development cycle: data collection scarcity, the absence of automated digital signal processing (DSP) tooling, dependency management complexity, hardware heterogeneity across embedded architectures, and the lack of a unified monitoring framework @hymel2023edge. These challenges are particularly acute in multi-sensor IoT applications, where raw data originates from heterogeneous physical sources and must be preprocessed consistently across both the training and inference stages.

Edge Impulse was selected as the primary development platform for this project due to its end-to-end MLOps architecture, which integrates data collection, DSP block configuration, neural network training, and C++ library deployment into a single coherent pipeline @hymel2023edge. The platform is specifically engineered for resource-constrained embedded targets — including ARM Cortex-M4 microcontrollers — and provides hardware-aware optimization through its EON Compiler, which directly generates optimized C++ kernel calls, reducing both RAM and Flash usage compared to standard TFLM deployment. For the Arduino UNO R4 WiFi, these constraints demand that preprocessing and inference operations be co-optimized from the outset.

=== Data Ingestion and Labeling Configuration

A new Edge Impulse project was initialized and configured to accept multi-channel time-series data from the five onboard sensors: smoke, VOC, CO, IR flame, and temperature/humidity. Data was ingested using the Edge Impulse CLI Data Forwarder, which streams live sensor readings from the target device via a serial USB connection at a sampling frequency of 10 Hz. This approach aligns with the platform's data-centric design philosophy, which prioritizes real-world, on-device data collection over reliance on synthetic or third-party datasets @hymel2023edge.

Each recorded sample was assigned one of three class labels: fire, no_fire, or false_alarm. The three-class taxonomy was established based on the documented inadequacy of binary fire/no-fire classifiers in distinguishing genuine combustion events from nuisance stimuli such as cooking fumes or alcohol vapors. Research demonstrates that TinyML models deployed on Cortex-M class microcontrollers can achieve reliable real-time multi-class inference when training datasets are curated with semantically distinct class boundaries @alajlan2022tinyml.

=== Target Hardware Configuration and Resource Profiling

Following data ingestion, the project was configured to target the ARM Cortex-M4 architecture, enabling the generating of hardware-specific latency, RAM, and Flash consumption estimates. Research reports that on Cortex-M4 platforms, preprocessing latency for spectral analysis blocks can equal or exceed neural network inference latency, making DSP-NN co-optimization a critical design consideration @hymel2023edge.

Resource budget constraints for the RA4M1 were established as follows: a maximum of 128 KB of SRAM allocated to the inference pipeline, and a Flash budget capped at 512 KB for the combined DSP and model binary. These limits align with documented deployment behavior for Cortex-M4-class microcontrollers, where post-training quantization from Float32 to Int8 reduces model storage by a factor of four while leveraging specialized instructions for single-cycle multiply-accumulate operations on 8-bit operands, enabling inference with negligible accuracy degradation @novac2021quantization.
