== Edge Intelligence and TinyML <sec:edge_intelligence>

The traditional architecture for Internet of Things (IoT) systems has historically relied on a cloud-centric model, where raw sensor data is transmitted to centralized servers for processing and decision-making. However, for life-safety applications such as fire detection, this paradigm introduces critical vulnerabilities related to network latency, bandwidth constraints, and single-point-of-failure risks. The emergence of Edge Intelligence—specifically Tiny Machine Learning (TinyML)—offers a decentralized alternative by enabling complex inference tasks to be performed directly on the microcontroller unit (MCU) at the sensing site. This section explores the theoretical advancements that facilitate this shift and their implications for autonomous fire sensing nodes.

=== The Transition from Cloud to Edge-Centric Sensing

The primary driver for Edge Intelligence in fire detection is the requirement for deterministic real-time response. Fire events are characterized by rapid non-linear growth; a delay of several seconds due to network congestion or cloud unavailability can be the difference between containment and catastrophic failure. By performing data fusion and classification locally, _Autonomous Sensing Nodes_ achieve sub-100 ms inference latencies, ensuring immediate triggering of alarm states regardless of connectivity status @alajlan2022tinyml. Furthermore, local processing mitigates the "data deluge" problem in large-scale deployments, as only high-level alerts or compressed telemetry are transmitted, significantly reducing the power consumption associated with wireless radio operation @Tummala2025TinyML.

The cloud-centric model presents three fundamental weaknesses in the context of fire safety. First, _latency_: typical cloud round-trip times range from 50 ms to over 500 ms depending on network conditions, and this variability is unacceptable for systems where deterministic response times are mandated by safety regulations. Second, _availability_: fire events frequently coincide with infrastructure damage—power outages, network disruptions, or physical destruction of communication equipment—precisely when detection is most critical. A cloud-dependent system becomes useless at the moment of greatest need. Third, _privacy_: continuous transmission of environmental sensor data to cloud servers potentially exposes sensitive information about occupant behavior and activity patterns @alajlan2022tinyml.

Edge computing addresses these weaknesses by shifting the inference workload to the sensor node itself. @khan2025advancements survey the evolution of edge computing paradigms for IoT safety systems, noting that the convergence of efficient neural network architectures and increasingly capable microcontrollers has made on-device inference a practical reality for applications previously considered too computationally demanding. The authors identify the Cortex-M4 processor class—used in the _Autonomous Sensing Node_—as a particularly suitable platform for TinyML deployment due to its hardware floating-point unit, DSP instructions, and deterministic interrupt handling.

=== Theoretical Foundations of TinyML

TinyML represents the intersection of machine learning and embedded systems, focusing on the optimization of deep learning models for devices with memory budgets typically under 256 KB of RAM and 1 MB of Flash @warden2019tinyml. The theoretical breakthrough enabling this is the realization that many neural network architectures exhibit significant redundancy—their full-precision parameters contain more information than is necessary for the classification task at hand.

The cornerstone optimization technique for TinyML is _quantization_, the process of reducing the numerical precision of a model's weights and activations. The most common approach is post-training quantization from 32-bit floating point (FP32) to 8-bit integer (INT8), which reduces the model's memory footprint by 75% with typically less than 1% loss in classification accuracy @das2025tiny. @novac2021quantization provide an in-depth analysis of quantization techniques for embedded inference, demonstrating that INT8 quantization not only reduces memory but also accelerates inference on processors that support integer arithmetic units, such as the Cortex-M4's DSP extension.

Beyond quantization, several complementary optimization strategies have been explored in the literature. _Weight pruning_ involves removing connections with near-zero weights, producing sparse model representations that can be efficiently stored and computed. _Knowledge distillation_ trains a smaller "student" model to approximate the outputs of a larger "teacher" model, transferring learned representations without the computational overhead @das2025tiny. _Neural Architecture Search_ (NAS) automates the design of network topologies that are specifically optimized for a target hardware platform's memory and computational constraints. While NAS is computationally expensive to perform, its outputs—compact, hardware-aware architectures—are well-suited for deployment on resource-constrained MCUs.

For fire detection specifically, these optimizations must be applied with care. Unlike image classification tasks where small accuracy degradations are tolerable, fire detection is a _safety-critical_ application where both false negatives (missed fires) and false positives (nuisance alarms) carry serious consequences. @samanta2024optimizing study the impact of quantization on classification confidence distributions, finding that INT8 quantization can compress the probability distribution of the model's outputs, making the model less certain in its predictions. This finding highlights the importance of validating quantized models not only on aggregate accuracy metrics but also on confidence calibration—the reliability of the model's reported confidence scores across all classes.

=== Advantages for Autonomous Fire Systems

The application of TinyML to fire sensing provides three fundamental advantages: autonomy, privacy, and reliability.

_Autonomy_ is achieved through the system's ability to maintain protective monitoring during network outages—a common occurrence during fire-induced power failures. The _Autonomous Sensing Node_ continues to perform local inference and trigger alarms even when completely disconnected from external infrastructure. This stand-alone capability is a critical differentiator from cloud-dependent IoT fire systems, which become inert during communication failures.

_Privacy_ is inherently preserved as raw environmental data never leaves the device. In an era of increasing regulatory scrutiny over data collection—exemplified by GDPR in the European Union—the ability to perform intelligent classification without transmitting occupant-level data is a significant architectural advantage @alajlan2022tinyml. Only high-level telemetry, such as classification labels and alert states, need be transmitted to external systems.

_Reliability_ is enhanced through the reduction of system complexity. By eliminating the dependency on external APIs or cloud services, the "attack surface" for system failure is minimized. The entire decision chain—from raw sensor reading to alarm state—resides within a single, deterministic firmware loop, making the system's behavior predictable and auditable.

As highlighted by @hymel2023edge, platforms like Edge Impulse have standardized the deployment of TinyML models, providing automated toolchains for data ingestion, feature engineering, model training, quantization, and C++ library export. This standardization has significantly lowered the barrier to entry for researchers and engineers seeking to deploy intelligent sensing on commodity microcontrollers, allowing for a rigorous, data-driven approach to fire detection that was previously only possible on high-power gateway devices. The _Autonomous Sensing Node_ leverages this ecosystem, using Edge Impulse as the primary model development and deployment platform, as detailed in the Implementation chapter.

=== Section Glossary

- *Edge Intelligence*: The paradigm of performing data processing and machine learning inference at the "edge" of the network, close to the data source, rather than in a centralized cloud.
- *TinyML (Tiny Machine Learning)*: A field of machine learning focused on developing models and algorithms capable of running on low-power, resource-constrained microcontrollers.
- *Quantization*: The process of mapping high-precision floating-point numbers to lower-precision integer representations to reduce the memory footprint and increase the inference speed of a model.
- *Inference Latency*: The time required for a machine learning model to process an input and generate a prediction.
- *Knowledge Distillation*: A technique where a smaller model is trained to replicate the behavior of a larger, more complex model, transferring learned capabilities at reduced computational cost.
